version: "3.7"
services:
  app:
    build:
      args:
        user: elsayed
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: socail-service
    container_name: socail-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - social

  db:
    image: mysql:8.0
    container_name: socail-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-config/mysql:/docker-entrypoint-initdb.d
    networks:
      - social


  phpmyadmin:
    image: phpmyadmin
    container_name: socail-phpmyadmin-db
    restart: always
    ports:
      - 8498:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 8000M

    networks:
      - social

  nginx:
    image: nginx:alpine
    container_name: socail-nginx
    restart: unless-stopped
    ports:
      - 7000:80
    volumes:
      - ./:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d/
    networks:
      - social


networks:
    social:
        driver: bridge
